CREATE TABLE user (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL
);

CREATE TABLE estratos (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  estrato INTEGER NOT NULL
);

CREATE TABLE valores (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  valor FLOAT (9,2),
  estrato_id INTEGER NOT NULL,
  FOREIGN KEY (estrato_id) REFERENCES estratos(id) ON DELETE CASCADE
);

CREATE TABLE servicios (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(64) NOT NULL,
  valor_id INTEGER NOT NULL,
  FOREIGN KEY (valor_id) REFERENCES valores(id) ON DELETE CASCADE
);

CREATE TABLE clientes (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nombres VARCHAR(64) NOT NULL,
  apellidos VARCHAR (64) NOT NULL,
  cedula VARCHAR(32) NOT NULL,
  telefono VARCHAR(32) NOT NULL,
  direccion VARCHAR (32) NOT NULL,
  sexo VARCHAR(16) NOT NULL,
  email VARCHAR(128) NOT NULL,
  UNIQUE (cedula)
);

CREATE TABLE facturas (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  servicio_id INTEGER NOT NULL,
  cliente_id INTEGER NOT NULL,
  FOREIGN KEY (servicio_id) REFERENCES servicios(id) ON DELETE CASCADE,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

CREATE TABLE consolidados (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cliente_id INTEGER NOT NULL,
  factura_id INTEGER NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
  FOREIGN KEY (factura_id) REFERENCES facturas(id) ON DELETE CASCADE
);

INSERT INTO `user` VALUES (1,'admin','4aae984230416ba76f98be2fd11e1aa71d90630a','julio.carvajal@outlook.com');
